### ISSUE TITLE
Understanding the Code

### ISSUE THREAD

**Issue by nirajkark07** [julienr/vertex_visibility#5]
Hello! 

Thank you for your work.

I am looking to use this code to render the vertices visible by a camera. Instead of a .ply file, I am using a .obj file. I have the 4x4 homogeneous transformation matrix of the obj file with respect to the camera.

I noticed that in the code you have K, R, and C defining the camera parameters. I know that K and R are the camera intrinsic and Rotation matrix. But, I am a bit confused on C, and what value I should use given that I have a 4x4 transformation of the object in the camera's coordinate system. Would you be able to provide some background information on this? 

Thank you so much!

**Comment by julienr** [comment]
(I am a bit rusty here, this code is pretty old)

C is the camera position in world coordinates and you can extract it from the rightmost column of you 4x4 camera matrix

![image](https://github.com/user-attachments/assets/82d0fd6a-24cf-4033-9f4f-50c6f5db3f47)

So like `C = -R^T * M[:3,3]` (assuming you camera matrix is M) or something along those lines. 

[These slides may be useful](https://www.cs.cmu.edu/~16385/s17/Slides/11.1_Camera_matrix.pdf)

**Comment by nirajkark07** [comment]
Awesome. Thank you for your help.
